version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/chat-app
      - JWT_SECRET=your_super_secret
      - PORT=5000
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:80
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
volumes:
  mongo-data: 